---
- name: Step3
  hosts: localhost
  vars:
    step3: |-
      Step 3
      Shake all together.
      
      
  tasks:
    - name: print step3
      ansible.builtin.debug:
        msg: "{{ step3.split('\n') }}"

    - ansible.builtin.pause:
        seconds: 5
        #prompt: Type ENTER to start
        echo: no

