---
- name: Step2
  hosts: localhost
  vars:
    step2: |-
      Step 2
      Add sugar and muddle until juices release.
      
      
  tasks:
    - name: print step2
      ansible.builtin.debug:
        msg: "{{ step2.split('\n') }}"

    - ansible.builtin.pause:
        seconds: 5
        #prompt: Type ENTER to start
        echo: no

