---
- name: Step4
  hosts: localhost
  vars:
    step4: |-
      Step 4
      Shake all together.
      
      
  tasks:
    - name: print step4
      ansible.builtin.debug:
        msg: "{{ step4.split('\n') }}"

    - ansible.builtin.pause:
        seconds: 5
        #prompt: Type ENTER to start
        echo: no

