---
- hosts: localhost
  connection: local
 
  vars:
    - name: step1

  tasks:
    - name: Step One
      debug:
        msg: "Status --> {{ step1 }}"

    - ansible.builtin.pause:
        seconds: 5
        #prompt: Type ENTER to start
        echo: no
