---
- name: Step1 
  hosts: localhost
  vars:
    step1: |-
      Step 1
      Squeeze and drop lime wedges into a large rocks glass.
      
      
  tasks:
    - name: print step1
      ansible.builtin.debug:
        msg: "{{ step1.split('\n') }}"

    - ansible.builtin.pause:
        seconds: 5
        #prompt: Type ENTER to start
        echo: no

