---
- name: step1

  vars_prompt:
    - name: step1
      prompt: Squeeze and drop lime wedges into a large rocks glass. 
      default: "OK"
      private: no

  tasks:
    - name: Step One
      debug:
        msg: "Status --> {{ step1 }}"

    - ansible.builtin.pause:
        seconds: 5
        #prompt: Type ENTER to start
        echo: no
